#include "GenerateurSignal.h"




int GenerateurSignal::ChoisirSignal()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-108--faccaa4:185ed112cd5:-8000:0000000000000B2C begin
{
    return 0;
}
// section 10--28--98-108--faccaa4:185ed112cd5:-8000:0000000000000B2C end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void GenerateurSignal::ChoisirFrequence()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-108--faccaa4:185ed112cd5:-8000:0000000000000B2E begin
{
}
// section 10--28--98-108--faccaa4:185ed112cd5:-8000:0000000000000B2E end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void GenerateurSignal::Achoisir amplitude ()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-108--faccaa4:185ed112cd5:-8000:0000000000000B30 begin
{
}
// section 10--28--98-108--faccaa4:185ed112cd5:-8000:0000000000000B30 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
