#include "Signal.h"




void Signal::CalculerEchantillons(int Amplitude, int DutyCycle)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-108--faccaa4:185ed112cd5:-8000:0000000000000B3A begin
{
}
// section 10--28--98-108--faccaa4:185ed112cd5:-8000:0000000000000B3A end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Signal::AfficherEchantillons()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-108--faccaa4:185ed112cd5:-8000:0000000000000B3E begin
{
}
// section 10--28--98-108--faccaa4:185ed112cd5:-8000:0000000000000B3E end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int Signal::GetPeriodeEch()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-108--faccaa4:185ed112cd5:-8000:0000000000000B40 begin
{
    return 0;
}
// section 10--28--98-108--faccaa4:185ed112cd5:-8000:0000000000000B40 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
