#include "triangle .h"




void triangle ::CalculerEchantillons(int Amplitude, int DutyCycle)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-108--faccaa4:185ed112cd5:-8000:0000000000000B44 begin
{
}
// section 10--28--98-108--faccaa4:185ed112cd5:-8000:0000000000000B44 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
