#include " Utilisateur.h"




void  Utilisateur::ObserverSignal()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-108--faccaa4:185ed112cd5:-8000:0000000000000B14 begin
{
}
// section 10--28--98-108--faccaa4:185ed112cd5:-8000:0000000000000B14 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void  Utilisateur::Configurergenerateur()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-108--faccaa4:185ed112cd5:-8000:0000000000000B16 begin
{
}
// section 10--28--98-108--faccaa4:185ed112cd5:-8000:0000000000000B16 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
