#include "GenerateurSignal.h"

#include <iostream>
using namespace std;




int GenerateurSignal::ChoisirSignal()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-45-3d268f01:18538974816:-8000:0000000000000A13 begin
{
}
// section 10--28--98-45-3d268f01:18538974816:-8000:0000000000000A13 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void GenerateurSignal::ChoisirFrequence()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-45-3d268f01:18538974816:-8000:0000000000000A15 begin
{
}
// section 10--28--98-45-3d268f01:18538974816:-8000:0000000000000A15 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void GenerateurSignal::ChoisirAmplitude()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-45-3d268f01:18538974816:-8000:0000000000000A15 begin
{
}
// section 10--28--98-45-3d268f01:18538974816:-8000:0000000000000A15 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

