#include "GenerateurSignal.h"




int GenerateurSignal::ChoisirSignal()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-67-3c5ab04f:185ed06e66b:-8000:0000000000000A14 begin
{
    return 0;
}
// section 10--28--98-67-3c5ab04f:185ed06e66b:-8000:0000000000000A14 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void GenerateurSignal::ChoisirFrequence()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-67-3c5ab04f:185ed06e66b:-8000:0000000000000A16 begin
{
}
// section 10--28--98-67-3c5ab04f:185ed06e66b:-8000:0000000000000A16 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void GenerateurSignal::ChoisirAmplitude()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-67-3c5ab04f:185ed06e66b:-8000:0000000000000A18 begin
{
}
// section 10--28--98-67-3c5ab04f:185ed06e66b:-8000:0000000000000A18 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
