#include "Signal.h"




int Signal::CalculerEchantillons(int Amplitude, int DutyCycle)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-67-3c5ab04f:185ed06e66b:-8000:0000000000000A1E begin
{
    return 0;
}
// section 10--28--98-67-3c5ab04f:185ed06e66b:-8000:0000000000000A1E end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Signal::AfficherEcantillons()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-67-3c5ab04f:185ed06e66b:-8000:0000000000000A20 begin
{
}
// section 10--28--98-67-3c5ab04f:185ed06e66b:-8000:0000000000000A20 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int Signal::GetPeriodeEch()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-67-3c5ab04f:185ed06e66b:-8000:0000000000000A2D begin
{
    return 0;
}
// section 10--28--98-67-3c5ab04f:185ed06e66b:-8000:0000000000000A2D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
