#include "Triangle.h"




void Triangle::CalculerEchantillons(int Amplitude, int DutyCycle)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-67-3c5ab04f:185ed06e66b:-8000:0000000000000A3F begin
{
}
// section 10--28--98-67-3c5ab04f:185ed06e66b:-8000:0000000000000A3F end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
