#include "Utilisateur.h"




void Utilisateur::ConfigurerGenerateur()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-67-3c5ab04f:185ed06e66b:-8000:0000000000000A3A begin
{
}
// section 10--28--98-67-3c5ab04f:185ed06e66b:-8000:0000000000000A3A end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Utilisateur::ObserverSignal()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-67-3c5ab04f:185ed06e66b:-8000:0000000000000A3C begin
{
}
// section 10--28--98-67-3c5ab04f:185ed06e66b:-8000:0000000000000A3C end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
