#include "GenerateurSignal.h"




int GenerateurSignal::ChoisirSignal()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-119-50896a21:185c8e49ee4:-8000:0000000000000B3C begin
{
    return 0;
}
// section 10--28--98-119-50896a21:185c8e49ee4:-8000:0000000000000B3C end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void GenerateurSignal::ChoisirFrequence()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-119-50896a21:185c8e49ee4:-8000:0000000000000B44 begin
{
    
}
// section 10--28--98-119-50896a21:185c8e49ee4:-8000:0000000000000B44 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void GenerateurSignal::ChoisirAmplitude()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-119-50896a21:185c8e49ee4:-8000:0000000000000B46 begin
{
    
}
// section 10--28--98-119-50896a21:185c8e49ee4:-8000:0000000000000B46 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
