#include "Signal.h"




void Signal::CalculerEchantillon(int Amplitude, int DutyCycle)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-119--22f287e8:185ed0cc660:-8000:0000000000000C80 begin
{
    
}
// section 10--28--98-119--22f287e8:185ed0cc660:-8000:0000000000000C80 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Signal::AfficherEchantillon()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-119--22f287e8:185ed0cc660:-8000:0000000000000C84 begin
{
    
}
// section 10--28--98-119--22f287e8:185ed0cc660:-8000:0000000000000C84 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int Signal::GetPeriodeEch()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-119--22f287e8:185ed0cc660:-8000:0000000000000C86 begin
{
    return 0;
}
// section 10--28--98-119--22f287e8:185ed0cc660:-8000:0000000000000C86 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
