#include "Triangle.h"




void Triangle::CalculerEchantillons(int Amplitude, int DutyCycle)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-119--22f287e8:185ed0cc660:-8000:0000000000000CA3 begin
{
    
}
// section 10--28--98-119--22f287e8:185ed0cc660:-8000:0000000000000CA3 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
