#include "Class Utilisateur.h"




void Class Utilisateur::ConfigurerGeneraeur()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98--98-59d91335:185ed107778:-8000:0000000000000B3C begin
{
    
}
// section 10--28--98--98-59d91335:185ed107778:-8000:0000000000000B3C end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Class Utilisateur::ObserverSignal()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98--98-59d91335:185ed107778:-8000:0000000000000B3E begin
{
    
}
// section 10--28--98--98-59d91335:185ed107778:-8000:0000000000000B3E end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
