#include "Classe Triangle.h"




void Classe Triangle::CalculerEchantillons()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98--98-59d91335:185ed107778:-8000:0000000000000B37 begin
{
    
}
// section 10--28--98--98-59d91335:185ed107778:-8000:0000000000000B37 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
