#include "Class Generateur signal.h"




int Class Generateur signal::ChoisirSignal()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98--98-59d91335:185ed107778:-8000:0000000000000B1B begin
{
    return 0;
}
// section 10--28--98--98-59d91335:185ed107778:-8000:0000000000000B1B end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Class Generateur signal::ChoisirFrequence()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98--98-59d91335:185ed107778:-8000:0000000000000B1D begin
{
    
}
// section 10--28--98--98-59d91335:185ed107778:-8000:0000000000000B1D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Class Generateur signal::ChoisirAmplitude()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98--98-59d91335:185ed107778:-8000:0000000000000B1F begin
{
    
}
// section 10--28--98--98-59d91335:185ed107778:-8000:0000000000000B1F end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
